#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('./app');
var debug = require('debug')('booksysmanager:server');
var http = require('http');
var https = require('https');
var fs = require("fs");

var options ={
  key:fs.readFileSync("./cert/1531060622054.key"),
  cert:fs.readFileSync("./cert/1531060622054.pem")
};

/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '4000');
//app.set('port', port);

/**
 * Create HTTP server.
 */



var HttpsServer = https.createServer(options,app).listen(443);
HttpsServer.on('error', onError);
HttpsServer.on('listening',onHttpsListening);

/**
 * Listen on provided port, on all network interfaces.
 */
var server = http.createServer(app);
server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  console.log('Listening on ' + bind);
}

 function onHttpsListening() {
  var addr = HttpsServer.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  console.log('onHttpsListening on ' + bind);
}

